CC = gcc
INCLUDES = -I ../include
SRC = src
OBJ = obj

INCLUDES = ./include

MAIN_CONSOLE = console.c
MAIN_FONT = font.c


CONSOLEDIR = ./console
# Исходники
SRCS_CONSOLE = $(filter-out $(CONSOLEDIR)/$(SRC)/$(MAIN_FONT), $(wildcard $(CONSOLEDIR)/$(SRC)/*.c))
SRCS_FONT = $(filter-out $(CONSOLEDIR)/$(SRC)/$(MAIN_CONSOLE), $(wildcard $(CONSOLEDIR)/$(SRC)/*.c))

# Объекты
OBJS_CONSOLE = $(SRCS_CONSOLE:$(CONSOLEDIR)/$(SRC)/%.c=$(CONSOLEDIR)/$(OBJ)/%.o)
OBJS_FONT = $(SRCS_FONT:$(CONSOLEDIR)/$(SRC)/%.c=$(CONSOLEDIR)/$(OBJ)/%.o)

# Исполняемые файлы
CONSOLE_EXE = $(CONSOLEDIR)/console
FONT_EXE = $(CONSOLEDIR)/font

COMPUTERDIR = ./mySimpleComputer
SRCS_COMPUTER = $(wildcard $(COMPUTERDIR)/$(SRC)/*c)
OBJS_COMPUTER = $(SRCS_COMPUTER:$(COMPUTERDIR)/$(SRC)/%.c=$(COMPUTERDIR)/$(OBJ)/%.o)
LIBCOMPUTER = mySimpleComputer
LIBCOMPUTERPATH = $(COMPUTERDIR)/lib$(LIBCOMPUTER).a

TERMDIR = ./myTerm
SRCS_TERM = $(wildcard $(TERMDIR)/$(SRC)/*.c)
OBJS_TERM = $(SRCS_TERM:$(TERMDIR)/$(SRC)/%.c=$(TERMDIR)/$(OBJ)/%.o)
LIBTERMINC = myTerm
LIBTERMPATH = $(TERMDIR)/lib$(LIBTERMINC).a

CHARSDIR = ./myBigChars
SRCS_CHARS = $(wildcard $(CHARSDIR)/$(SRC)/*.c)
OBJS_CHARS = $(SRCS_CHARS:$(CHARSDIR)/$(SRC)/%.c=$(CHARSDIR)/$(OBJ)/%.o)
LIBCHARSC = myBigChars
LIBCHARSPATH = $(CHARSDIR)/lib$(LIBCHARSC).a

KEYDIR = ./myReadKey
SRCS_KEY = $(wildcard $(KEYDIR)/$(SRC)/*.c)
OBJS_KEY = $(SRCS_KEY:$(KEYDIR)/$(SRC)/%.c=$(KEYDIR)/$(OBJ)/%.o)
LIBKEYC = myReadKey
LIBKEYPATH = $(KEYDIR)/lib$(LIBKEYC).a

all: console font

console: $(OBJS_CONSOLE) $(LIBCOMPUTERPATH) $(LIBTERMPATH) $(LIBCHARSPATH) $(LIBKEYPATH)
	$(CC) $(OBJS_CONSOLE) -L $(COMPUTERDIR) -L $(TERMDIR) -L $(CHARSDIR) -L $(KEYDIR) -l$(LIBCOMPUTER) -l$(LIBTERMINC) -l$(LIBCHARSC) -l$(LIBKEYC) -o ./console/console

font: $(LIBCOMPUTERPATH) $(LIBTERMPATH) $(LIBCHARSPATH) $(OBJS_FONT) $(LIBKEYPATH)
	$(CC) $(OBJS_FONT) -L $(COMPUTERDIR) -L $(TERMDIR) -L $(CHARSDIR) -l$(LIBCOMPUTER) -L $(KEYDIR) -l$(LIBTERMINC) -l$(LIBCHARSC) -l$(LIBKEYC) -o ./console/font

$(CONSOLEDIR)/$(OBJ)/%.o: $(CONSOLEDIR)/$(SRC)/%.c
	$(CC) -c -I $(INCLUDES) $< -o $@


$(LIBCOMPUTERPATH): $(OBJS_COMPUTER)
	ar rcs $(LIBCOMPUTERPATH) $(OBJS_COMPUTER)

$(COMPUTERDIR)/$(OBJ)/%.o: $(COMPUTERDIR)/$(SRC)/%.c
	$(CC) -c -I $(INCLUDES) $< -o $@



$(LIBTERMPATH): $(OBJS_TERM)
	ar rcs $(LIBTERMPATH) $(OBJS_TERM)

$(TERMDIR)/$(OBJ)/%.o: $(TERMDIR)/$(SRC)/%.c
	$(CC) -c -I $(INCLUDES) $< -o $@


$(LIBCHARSPATH): $(OBJS_CHARS)
	ar rcs $(LIBCHARSPATH) $(OBJS_CHARS)

$(CHARSDIR)/$(OBJ)/%.o: $(CHARSDIR)/$(SRC)/%.c
	$(CC) -c -I $(INCLUDES) $< -o $@

$(LIBKEYPATH): $(OBJS_KEY)
	ar rcs $(LIBKEYPATH) $(OBJS_KEY)

$(KEYDIR)/$(OBJ)/%.o: $(KEYDIR)/$(SRC)/%.c
	$(CC) -c -I $(INCLUDES) $< -o $@

clean:
	rm -rf $(OBJS_CONSOLE) $(OBJS_TERM) $(OBJS_COMPUTER) $(OBJS_CHARS) $(OBJS_KEY) $(LIBTERMPATH) $(LIBCOMPUTERPATH) $(LIBCHARSPATH) $(LIBKEYPATH) $(CONSOLE_EXE) $(FONT_EXE)