CC = gcc
INCLUDES = -I ../include
SRC = src
OBJ = obj

INCLUDES = ./include

CONSOLEDIR = ./console
SRCS_CONSOLE = $(wildcard $(CONSOLEDIR)/$(SRC)/*.c)
OBJS_CONSOLE = $(SRCS_CONSOLE:$(CONSOLEDIR)/$(SRC)/%.c=$(CONSOLEDIR)/$(OBJ)/%.o)

COMPUTERDIR = ./mySimpleComputer
SRCS_COMPUTER = $(wildcard $(COMPUTERDIR)/$(SRC)/*c)
OBJS_COMPUTER = $(SRCS_COMPUTER:$(COMPUTERDIR)/$(SRC)/%.c=$(COMPUTERDIR)/$(OBJ)/%.o)
LIBCOMPUTER = mySimpleComputer
LIBCOMPUTERPATH = $(COMPUTERDIR)/lib$(LIBCOMPUTER).a

TERMDIR = ./myTerm
SRCS_TERM = $(wildcard $(TERMDIR)/$(SRC)/*.c)
OBJS_TERM = $(SRCS_TERM:$(TERMDIR)/$(SRC)/%.c=$(TERMDIR)/$(OBJ)/%.o)
LIBTERMINC = myTerm
LIBTERMPATH = $(TERMDIR)/lib$(LIBTERMINC).a

CHARSDIR = ./myBigChars
SRCS_CHARS = $(wildcard $(CHARSDIR)/$(SRC)/*.c)
OBJS_CHARS = $(SRCS_CHARS:$(CHARSDIR)/$(SRC)/%.c=$(CHARSDIR)/$(OBJ)/%.o)
LIBCHARSC = myBigChars
LIBCHARSPATH = $(CHARSDIR)/lib$(LIBCHARSC).a

all: ./console/console

./console/console: $(OBJS_CONSOLE) $(LIBCOMPUTERPATH) $(LIBTERMPATH) $(LIBCHARSPATH)
	$(CC) $(OBJS_CONSOLE) -L $(COMPUTERDIR) -L $(TERMDIR) -L $(CHARSDIR) -l$(LIBCOMPUTER) -l$(LIBTERMINC) -l$(LIBCHARSC) -o ./console/console

$(CONSOLEDIR)/$(OBJ)/%.o: $(CONSOLEDIR)/$(SRC)/%.c
	$(CC) -c -I $(INCLUDES) $< -o $@


$(LIBCOMPUTERPATH): $(OBJS_COMPUTER)
	ar rcs $(LIBCOMPUTERPATH) $(OBJS_COMPUTER)

$(COMPUTERDIR)/$(OBJ)/%.o: $(COMPUTERDIR)/$(SRC)/%.c
	$(CC) -c -I $(INCLUDES) $< -o $@



$(LIBTERMPATH): $(OBJS_TERM)
	ar rcs $(LIBTERMPATH) $(OBJS_TERM)

$(TERMDIR)/$(OBJ)/%.o: $(TERMDIR)/$(SRC)/%.c
	$(CC) -c -I $(INCLUDES) $< -o $@


$(LIBCHARSPATH): $(OBJS_CHARS)
	ar rcs $(LIBCHARSPATH) $(OBJS_CHARS)

$(CHARSDIR)/$(OBJ)/%.o: $(CHARSDIR)/$(SRC)/%.c
	$(CC) -c -I $(INCLUDES) $< -o $@

clean:
	rm -rf $(OBJS_CONSOLE) $(OBJS_TERM) $(OBJS_COMPUTER) $(OBJS_CHARS) $(LIBTERMPATH) $(LIBCOMPUTERPATH) $(LIBCHARSPATH) ./console/console